### ISSUE TITLE
incorrect privacy api 

### ISSUE THREAD

**Issue by danmarsden** [institut-agro-ead/moodle_report_modulecompletion#1]
The privacy api class implemented is the null provider, suggesting that your plugin doesn't store any user specific information, but it contains a table within the plugin that contains a userid field - suggesting that it does in fact store user data. 

You should either delete the null privacy provider class or implement a correct privacy api class that covers this table.

**Comment by institut-agro-ead** [comment]
It should now be correctly implemented.
