### ISSUE TITLE
Students progress not showing results from quizzes with "receive a passing grade" to complete.

### ISSUE THREAD

**Issue by maodoanminnh** [institut-agro-ead/moodle_report_modulecompletion#12]
Hi. 
I found that all the modules that students can mark as done or view to complete will be shown correctly in the report once marked or viewed, but all the quizzes which requires "receive a passing grade" or "receive a grade" will not be shown in the report as completed although they've been completed and marked as done:receive a passing grade. 

Completion tracking in the course is enabled and I could use the custom report builder to show the completion progress correctly. I don't know if there're wrong configurations somewhere. Could you please help?

I've attached 2 images, the first showing the result on the report, while the second showing the actual completion status of the student. The time I filtered starts from the beginning of the course to the present. Actually all these sample activities were created and completed within minutes to test the plugin.
 
Thank you.
Mao

PS. I prefer your plugin because it can show progress over a specified period, which is very useful to track students' performance over a week or month during the academic year. Thank you very much.

<img width="1054" alt="image" src="https://github.com/institut-agro-ead/moodle_report_modulecompletion/assets/89524105/e886a450-c1c4-4210-ab89-e1b360f90d15">

<img width="1352" alt="image" src="https://github.com/institut-agro-ead/moodle_report_modulecompletion/assets/89524105/fb7fbd5e-2937-4db7-9dc6-51fecf3d4bdf">

**Comment by institut-agro-ead** [comment]
Hello, thank you for reporting this.
To be honest, we designed this plugin many years ago (back to Moodle 3.6 I believe) and we never encountered that issue before. I believe our platforms never used quizzes in that manner (we mainly use H5P activities).
Anyway I think we are going to have to investigate, but it has something to do with the completion status stored in the database. It must be different for this scenario and the query probably does not handle that case.

**Comment by institut-agro-ead** [comment]
Fixed with latest release.
