### ISSUE TITLE
an error i cannot understand

### ISSUE THREAD

**Issue by sH0k3n122** [institut-agro-ead/moodle_report_modulecompletion#13]
Hi!
I use two version of moodle site - one 'original' and one that is a copy of the original site, where I test all plugins etc.
I installed the plugin in the copied site and it's working great, but the problem is on the original site. I keep receiving this error:
`core_plugin_manager::remove_plugin_folder(): Argument #1 ($plugin) must be of type core\plugininfo\base, null given, called in [dirroot]/lib/classes/plugin_manager.php on line 1425`

Can you help me? :(

**Comment by institut-agro-ead** [comment]
Hello,
this does not appear to be related to the plugin itself but more to the installation process. Are you sure you are using the same version and the same server configuration ? That might also be a folder/file permission access problem ?

**Comment by sH0k3n122** [comment]
I am 100% sure it is the same version and the same server configuration. When I was installing some plugins at the beggining it was the folder/file permission access problem, but I gave the right permissions to the folder and it worked ahead.
I actually managed to go past the site with that problem, but now the installation process is stuck at "to be installed" status.

**Comment by institut-agro-ead** [comment]
Well we can’t reproduce the problem and honestly it does not seem to be a problem originating from our plugin judging from the error (Moodle seems to fail to remove a folder, hence the permission question).
Have you tried to purge all caches from the admin CLI ?
What exact version of Moodle are you using ?
