### ISSUE TITLE
plugins submitted to plugins db must support postgres and mysql based databases

### ISSUE THREAD

**Issue by danmarsden** [institut-agro-ead/moodle_report_modulecompletion#6]
your sql code contains Mysql specific functions like FROM_UNIXTIME() DATE_FORMAT() that will not work on a postgres install. Please test your plugin on a postgres site and fix any database query incompatibility issues.

this is a blocker for plugins db approval.

**Comment by institut-agro-ead** [comment]
Plugin tested on both mysql and postgres platforms. Dates transformation is now done after the query, with PHP.
