### ISSUE TITLE
hard-coded roleids in sql

### ISSUE THREAD

**Issue by danmarsden** [institut-agro-ead/moodle_report_modulecompletion#7]
https://github.com/institut-agro-ead/moodle_report_modulecompletion/blob/main/locallib.php#L344

roleid = 5 could be different or not even used on many sites - please ensure you don't hard-code values like this.

note this is a blocker for plugins db approval.

**Comment by institut-agro-ead** [comment]
The role id has been replaced by a specific capability (`moodle/course:isincompletionreports`) that will allow the query to only fetch users that are in the completion reports.
I hope this approach is better.
